---
fireactions_version: 0.1.1
fireactions_arch: amd64
# (konradasb): TODO: Change this to GitHub releases after public release.
fireactions_url: |
  https://storage.googleapis.com/fireactions/fireactions-v{{ fireactions_version }}-linux-{{ fireactions_arch }}.tar.gz
fireactions_install_dir: /opt/fireactions/{{ fireactions_version }}
fireactions_group: root
fireactions_owner: root
fireactions_service_state: started

fireactions_config_dir: /etc/fireactions
fireactions_config_file_path: "{{ fireactions_config_dir }}/config.yaml"
fireactions_config: {}
