---
name: release-please

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: read
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run release-please
      uses: google-github-actions/release-please-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
