---
name: release-please

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: read
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get GitHub token
      uses: actions/create-github-app-token@v1
      id: get_token
      with:
        app-id: ${{ secrets.HOSTINGERBOT_APP_ID }}
        private-key: ${{ secrets.HOSTINGERBOT_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        repositories: |
          ansible-collection-fireactions

    - name: Run release-please
      uses: google-github-actions/release-please-action@v4
      with:
        token: ${{ steps.get_token.outputs.token }}
